-- MySQL Script generated by MySQL Workbench
-- Mon Oct 28 17:50:32 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`roles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`roles` (
  `id` INT NOT NULL,
  `name` ENUM('USER', 'ADMIN') NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `roles_id` INT NOT NULL,
  PRIMARY KEY (`id`, `roles_id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  INDEX `fk_users_roles_idx` (`roles_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_roles`
    FOREIGN KEY (`roles_id`)
    REFERENCES `mydb`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user_info` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user_info` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(45) NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `users_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `users_id`),
  UNIQUE INDEX `phone_number_UNIQUE` (`phone_number` ASC) VISIBLE,
  INDEX `fk_user_info_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_info_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sensor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sensor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sensor` (
  `id` INT NOT NULL,
  `sensor_type` ENUM('smoke', 'temperature') NOT NULL,
  `location` VARCHAR(100) NOT NULL,
  `active` TINYINT NOT NULL,
  `create_at` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sensors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sensors` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sensors` (
  `id` INT NOT NULL,
  `sensor_type` ENUM('smoke', 'temperature') NOT NULL,
  `location` VARCHAR(100) NOT NULL,
  `status` ENUM('active', 'inactive') NOT NULL,
  `create_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`alerts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`alerts` ;

CREATE TABLE IF NOT EXISTS `mydb`.`alerts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `alert_type` ENUM('smoke', 'fire', 'temperature') NOT NULL,
  `alert_time` TIMESTAMP NULL DEFAULT current_timestamp,
  `severity` ENUM('low', 'medium', 'high') NOT NULL,
  `message` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`notifications`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`notifications` ;

CREATE TABLE IF NOT EXISTS `mydb`.`notifications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `notification_time` TIMESTAMP NOT NULL DEFAULT current_timestamp,
  `message` TEXT NULL,
  `alerts_id` INT NOT NULL,
  `users_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_notifications_alerts1_idx` (`alerts_id` ASC) VISIBLE,
  INDEX `fk_notifications_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_notifications_alerts1`
    FOREIGN KEY (`alerts_id`)
    REFERENCES `mydb`.`alerts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_notifications_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
